name: Backend

on:
  push:
    branches:
      - master
    paths:
      - backend/**
      - .github/workflows/**

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: set hash
        run: |
          echo "hash=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - uses: docker/build-push-action@v3
        with:
          context: backend/
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.hash }}
            ghcr.io/${{ github.repository }}:latest

