name: Frontend

on:
  push:
    branches:
      - master
    paths:
      - backend/**
      - .github/workflows/**

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: setup js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
          cache-dependency-path: ./frontend/yarn.lock
      - name: build frontend
        working-directory: ./frontend
        run: |
          yarn install --frozen-lockfile
          yarn run build
      
      - name: deploy site
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist